name: 'YAML Update Action'
description: 'Update the property of an existing YAML File'
author: 'Frank Jogeleit <frank.jogeleit@web.de>'
inputs:
  valueFile:
    required: true
    description: 'YAML file which should be updated'
  propertyPath:
    required: true
    description: 'Property Path - using dot for nesting: e.g. backend.version'
  value:
    required: true
    description: 'New property value'
  branch:
    required: false
    description: 'Branch to commit the change, will be created if not exist'
    default: 'master'
  targetBranch:
    required: false
    description: 'Target Branch for the created PullRequest'
    default: master
  createPR:
    required: false
    description: 'Create a PullRequest to the configured target branch'
    default: 'false'
  commitChange:
    required: false
    description: 'Commit the change "branch" with the given "message"'
    default: 'true'
  updateFile:
    required: false
    description: 'Update the original File in your workflow'
    default: 'false'
  message:
    required: false
    description: 'Commit message for the value update'
    default: ''
  token:
    required: false
    description: 'GitHub AuthToken for Athorization'
    default: ${{ github.token }}
  repository:
    required: false
    description: 'repoistory to update'
    default: ${{ github.repository }}
  workDir:
    required: false
    description: 'repository workspace location'
    default: .
runs:
  using: 'node12'
  main: 'dist/index.js'
